"""Home / Overview page."""
import streamlit as st

from lib import charts, data, metrics

d = data.load_all()
customers, products, subs, usage = d["customers"], d["products"], d["subscriptions"], d["usage"]

st.title("🌐 Customer & Product 360 Platform")
st.markdown(
    "Self-service intelligence across product usage, customer segmentation, and monetization. "
    "Designed for sales, product, and customer-success teams to answer their own questions about "
    "pricing, adoption, and churn risk."
)

kpi = metrics.kpi_summary(customers, usage)
c1, c2, c3, c4 = st.columns(4)
c1.metric("Total MRR", f"${kpi['total_mrr']/1000:,.0f}K")
c2.metric("Active customers", f"{kpi['active_customers']:,}")
c3.metric("% over-utilized", f"{kpi['pct_over']:.0f}%")
c4.metric("% under-utilized", f"{kpi['pct_under']:.0f}%")

st.markdown("---")

left, right = st.columns(2)
with left:
    st.plotly_chart(
        charts.regional_bar(metrics.mrr_by_region(customers), "mrr_usd", "MRR by region"),
        width="stretch",
    )
with right:
    st.plotly_chart(
        charts.horizontal_adoption(metrics.product_adoption(subs, products, customers)),
        width="stretch",
    )

st.markdown("---")

last_util = metrics.latest_utilization_per_sub(usage)
cust_avg = last_util.groupby("customer_id")["utilization_pct"].mean()
st.plotly_chart(charts.utilization_segments(cust_avg.tolist()), width="stretch")

st.markdown("---")
st.caption("Data is synthetic — generated by `scripts/generate_data.py` (seed=42). See README for schema.")

# ── Export ────────────────────────────────────────────────────────────────────
st.subheader("📊 Export to Google Slides")
st.caption("Download a .pptx → upload to Google Drive → opens as Google Slides automatically.")
if st.button("⬇ Download Platform Overview deck"):
    from lib.export_pptx import overview_deck
    mrr_region = metrics.mrr_by_region(customers)
    adoption   = metrics.product_adoption(subs, products, customers)
    pptx_bytes = overview_deck(kpi, mrr_region, adoption)
    st.download_button("📥 Save .pptx", data=pptx_bytes,
                       file_name="platform_overview.pptx",
                       mime="application/vnd.openxmlformats-officedocument.presentationml.presentation")
